using EmployeeClock.DAL;
using EmployeeClock.Model;
using EmployeeClock.Services.Interfaces;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace EmployeeClock.Services
{
    internal class EmployeeService : IEmployeeService
    {

        #region constants

        public const string TableName = "Employees";
        public const string Col_id = "ID";              // autogenerated, cannot be specified in insert/update
        public const string Col_tz = "EmployeeNat";
        public const string col_fname = "FirstName";
        public const string col_lname = "LastName";

        #endregion


        public bool Create(EmpInfo empInfo)
        {
            string query = $"INSERT INTO " +
                $"{TableName}({Col_tz},{col_fname},{col_lname})" +
                $"VALUES({empInfo.EmployeeNat},{empInfo.FirstName},{empInfo.LastName});";

            var dt = _dbContext.MakeQuery(query);
            return dt != null;
        }

        public EmpInfo? GetById(int id)
        {
            string query = $"SELECT * FROM {TableName} WHERE {Col_id} = {id}";
            DataTable? dt = DBContext.MakeQuery(query);

            if (dt != null && dt.Rows.Count > 0)
            {

                EmpInfo empInfo = new EmpInfo
                (
                   Convert.ToInt32(dt.Rows[0][Col_id]),
                   dt.Rows[0][Col_tz].ToString(),
                   dt.Rows[0][col_fname].ToString(),
                   dt.Rows[0][col_lname].ToString()
                );
                return empInfo;
            }
            else
            {
                return null; // No record found with the given ID
            }
        }

        public EmpInfo GeyByTz(string tz)
        {
            string query = $"SELECT * FROM {TableName} WHERE {Col_tz} = {tz}";
            DataTable? dt = DBContext.MakeQuery(query);

            if (dt != null && dt.Rows.Count > 0)
            {

                EmpInfo empInfo = new EmpInfo
                (
                   Convert.ToInt32(dt.Rows[0][Col_id]),
                   dt.Rows[0][Col_tz].ToString(),
                   dt.Rows[0][col_fname].ToString(),
                   dt.Rows[0][col_lname].ToString()
                );
                return empInfo;
            }
            else
            {
                return null; // No record found with the given ID
            }
        }

        public bool Delete(EmpInfo empInfo)
        {
            string query = $"DELETE FROM {TableName} WHERE {Col_id} = '{empInfo.ID}'";

            var dt = DBContext.MakeQuery(query);
            return dt != null;
        }

        public bool Update(EmpInfo empInfo)
        {
            
               
            string query = $"UPDATE {TableName} SET " +
                           $"{Col_tz} = '{empInfo.EmployeeNat}', " +
                           $"{col_fname} = '{empInfo.FirstName}', " +
                           $"{col_lname} = '{empInfo.LastName}' " +
                           $"WHERE {Col_id} = '{empInfo.ID}'";

            
            var dt = DBContext.MakeQuery(query);

            
            return dt != null;
            
        }

    }
}
